name : ROOT-cpm

on:
  schedule:
    - cron: 0 12 * * *

jobs:
  perl:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: apt-get update
        run: sudo apt-get update
      - name: Install non alienazed dependencies
        run: sudo apt-get install libx11-dev libxpm-dev
      - name: Install alien
        run: curl -sL https://git.io/cpm | perl - install --show-build-log-on-failure --test --configure-timeout=1920 Alien::ROOT
